### ISSUE TITLE
[Bug] - scan field to struct.

### ISSUE THREAD

**Issue by lkzcover** [stephenafamo/scan#7] opened 2024-01-26 00:02 UTC
Hi! I found this bug when I tried to scan a jsonb field into a structure.

In the file: [github.com/stephenafamo/scan@v0.5.0/source.go](https://github.com/stephenafamo/scan/blob/9ba867a0d6320411a251c4dda4923466a87d5d80/source.go#L216) in the [setMappings](https://github.com/stephenafamo/scan/blob/9ba867a0d6320411a251c4dda4923466a87d5d80/source.go#L143) method, when reflect encounters a structure in line 216 and goes into recursion, after exiting it, the method does not add a mapper for the structure itself (only for its fields) because use continue.

https://github.com/stephenafamo/scan/blob/9ba867a0d6320411a251c4dda4923466a87d5d80/source.go#L216-L218

Because of this, in the file github.com/stephenafamo/scan@v0.5.0/row.go, in https://github.com/stephenafamo/scan/blob/9ba867a0d6320411a251c4dda4923466a87d5d80/row.go#L86-L95, the library return error "No destination for column %s" because not found object in scanDestinations

You can also check this bug in [mapper_struct.go](https://github.com/stephenafamo/scan/blob/9ba867a0d6320411a251c4dda4923466a87d5d80/mapper_struct.go#L120), function [mapperFromMapping](https://github.com/stephenafamo/scan/blob/9ba867a0d6320411a251c4dda4923466a87d5d80/mapper_struct.go#L117), in line https://github.com/stephenafamo/scan/blob/9ba867a0d6320411a251c4dda4923466a87d5d80/mapper_struct.go#L120 you can notice that filterColumn returns one element less than expected in capacity.

In my test case 10 field and one of this was be struct
![Снимок экрана 2024-01-26 в 04 57 12](https://github.com/stephenafamo/scan/assets/2657587/1b19d6cf-ad02-47f0-9e36-9b1fb2904ada)

I changed the [setMappings](https://github.com/stephenafamo/scan/blob/9ba867a0d6320411a251c4dda4923466a87d5d80/source.go#L143) and it worked for me
```	
	if fieldType.Kind() == reflect.Struct {
		*m = append(*m, mapinfo{
			name:      key,
			position:  currentIndex,
			init:      inits,
			isPointer: isPointer,
		})
		s.setMappings(field.Type, key, v.copy(), m, inits, currentIndex...)
		continue
	}
```

p.s. sorry for my English

**Comment by stephenafamo** [comment] 2024-01-26 01:50
> when reflect encounters a structure in line 216 and goes into recursion, after exiting it, the method does not add a mapper for the structure itself (only for its fields)

This is the expected behaviour because it expects that if you add a `struct` then you want to scan into the fields of the struct.

If the struct itself was also added as a destination, then it would overwrite the other scans.

If you want to treat the struct as a scan destination, then it should implement one of the `scannableTypes` which by default is [`database/sql.Scanner`](https://pkg.go.dev/database/sql#Scanner)

**Comment by lkzcover** [comment] 2024-01-26 05:56
> If you want to treat the struct as a scan destination, then it should implement one of the scannableTypes which by default is [database/sql.Scanner](https://pkg.go.dev/database/sql#Scanner)

Yes, your right, thank you for your answer. But your's library already have scan into the fields of the struct. 

However i add this Scan implement  to my struct 
```
func (s <StructName>) Scan(src any) error {
	return nil
}
```
It's way see small strange for me, but work is perfect. A have all struct field in return pgxscan.One

**Comment by stephenafamo** [comment] 2024-01-26 13:23
I am sorry, I do not completely understand you so I am unsure if there is a bug or not.

I will close this issue now, but if you can send a PR I will be happy to review.

**Closed as completed by stephenafamo** 2024-01-26 13:23 UTC
Labels: invalid
